name: Setup Node
description: Setup Node

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: "16"

    - id: pnpm-cache-dir-path
      run: echo "dir=$(pnpm cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

    - run: pnpm install
      shell: bash
